### ISSUE TITLE
API v10

### ISSUE THREAD

**Issue by mwight4** [CPCStrategy/bing-ads-sdk-php#21]
As Microsoft has said they are discounting v9 this year as the quote from the blog show, I was wondering when we may see an update to the sdk for v10.
> We will sunset and remove v9 Campaign Management, Bulk, Optimizer and Ad Intelligence services at the end of calendar Q2 2016. Please migrate your applications from v9 to v10 at your earliest convenience. To help with your migration, we have provided a guide for migration from Bing Ads API V9 to v10.

Thanks for this sdk it has made my job automating some of our inhouse ppc work so much easier
Matt

**Comment by onema** [comment]
@mwight4 I'm glad you are using the library and it is useful!

I have a work in progress of `v10` [here](https://github.com/onema/bing-ads-sdk-php/tree/v10-sdk-11-16-2015). This is version 11/16/2015 but give it a try and let me know how well it works. 

I'm planning to wrap it up and send a new PR as soon as the pending PR for gets merged and tagged, although I need to make sure @dweichel and the CPCStrategy team review it.
