### ISSUE TITLE
Update SDK to use version 10 of the API

### ISSUE THREAD

**Issue by onema** [CPCStrategy/bing-ads-sdk-php#22]
Microsoft will be [removing](http://blogs.msdn.com/b/bing_ads_api/archive/2015/10/23/announcing-the-general-availability-of-the-bing-ads-api-and-sdk-version-10.aspx) v9 of the API at the end of Q2 2016 

> We will sunset and remove v9 Campaign Management, Bulk, Optimizer and Ad Intelligence services at the end of calendar Q2 2016. Please migrate your applications from v9 to v10 at your earliest convenience. To help with your migration, we have provided a [guide for migration from Bing Ads API v9 to v10](https://msdn.microsoft.com/en-US/library/bing-ads-api-version-10-migration-guide.aspx).

also see [BingAds api in PHP](https://code.msdn.microsoft.com/Bing-Ads-API-Version-9-in-fb27761f) and #21

**Comment by wpeereboom** [comment]
Would be great if we could improve this to v10

**Comment by swordbeta** [comment]
We have a fork containing both v9 and v10 as you need both to fully use the Bing Ads API: https://github.com/ExpandOnline/bing-ads-sdk-php
This however does break backwards compability due to adding v9 and v10 in the namespace.

**Comment by onema** [comment]
I also have this worki-in-progress fork only for version 10. I need to update the version, but in the meantime you can give it a try and let me know if you find any issues with it. 

https://github.com/onema/bing-ads-sdk-php/tree/v10-sdk-11-16-2015

**Comment by onema** [comment]
I have released `v2.1.0` which corresponds to the latest SDK for API V9 12/15/2015. This version will live in the branch `v2.x` moving forward (this is if they release new updates between now and the EOL of the API)

I have also released `v3.0.0` for the latest SDK for API V10 12/15/2015. 

Sorry for the delay @wpeereboom, @swordbeta and @MethorZ, please open an issue if you find any problems with these new versions.
