### ISSUE TITLE
Reports API is still in v9. 

### ISSUE THREAD

**Issue by ghost** [CPCStrategy/bing-ads-sdk-php#27]
Would be nice to include version 9 as well to maximize compatibility.

**Comment by onema** [comment]
Yes, I'm sorry. I thought I tagged it. Version 9 lives in the `v2.x` branch now. I updated the branch but must have forgotten to tag it. 

Just did, please use `v2.2`

Version 10 lives in the master branch and has been tagged as `v3.0`. Let me know if you have any issues with it.
